#! /bin/sh
# $Id: create_dir 5582 2007-08-05 03:16:58Z mburo $

# create a directory if neither link nor directory exist

d=$1

if [ "$d" = "" ]
then
  echo "empty dir" 
  exit 10
fi

if [ -L $d ]; then exit 0; fi
if [ -e $d ]; then exit 0; fi

mkdir -p $d
