/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TileCoderJNI */

#ifndef _Included_TileCoderJNI
#define _Included_TileCoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TileCoderJNI
 * Method:    tiles
 * Signature: ([III[DI[II)V
 */
JNIEXPORT void JNICALL Java_TileCoderJNI_tiles
  (JNIEnv *, jclass, jintArray, jint, jint, jdoubleArray, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
