#line 2 "coach_lang_tok.cc"

#line 4 "coach_lang_tok.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer RCSSCLangFlexLexerFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *RCSSCLangFlexLexeralloc (yy_size_t  );
void *RCSSCLangFlexLexerrealloc (void *,yy_size_t  );
void RCSSCLangFlexLexerfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include "coach_lang_tok.h"
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int RCSSCLangLexer::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[335] =
    {   0,
        0,    0,  108,  106,   99,   99,  106,  106,    1,    2,
       97,   95,   96,  106,   98,  100,   89,  106,   94,  105,
      105,  105,   37,   36,  105,  105,  105,  105,  105,  105,
      105,  105,   35,  105,  105,   38,  105,  105,  105,    3,
        4,   99,   92,    0,    0,  101,  102,  100,    0,   90,
       91,   93,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,    0,    0,    0,    0,   39,    0,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,   82,  105,
       50,  105,    0,    0,    0,    0,   23,  105,  105,  105,

        0,    0,  105,  105,  105,  105,  105,  104,    0,  103,
      105,  105,   84,   49,   22,  105,   53,  105,  105,   30,
        0,    0,    0,    0,    0,    0,    0,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,   51,  105,   83,  105,  105,   42,
       41,    0,    0,   28,    0,  105,   26,   24,  105,    5,
        0,  105,  105,   25,  105,  105,  105,   19,  105,  105,
       27,  105,   47,    0,    0,    0,    0,    0,   40,    0,
      105,  105,  105,  105,  105,  105,    6,   78,   29,  105,
       12,  105,  105,  105,   31,    9,  105,   20,  105,  105,

      105,  105,   75,    0,   46,   21,   81,    0,  105,   70,
       44,  105,   74,  105,  105,  105,  105,    0,    0,   43,
        0,    0,   88,    0,   45,  105,  105,  105,  105,  105,
      105,  105,  105,   34,  105,  105,  105,  105,  105,   32,
       87,   33,  105,  105,  105,    0,   52,   77,  105,  105,
      105,   13,   69,   68,   48,   63,   62,   14,   85,    0,
       61,   60,  105,   67,   66,   65,   64,  105,  105,   59,
       58,   57,   56,  105,  105,  105,    0,   80,  105,  105,
       18,   15,   16,   17,   76,  105,  105,  105,  105,  105,
      105,   55,  105,  105,    0,   10,  105,  105,  105,  105,

      105,  105,  105,    0,   73,   79,  105,   71,   72,   54,
      105,   86,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,    7,
      105,   11,    8,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    1,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    1,   15,
       16,   17,   18,    1,   19,   19,   19,   19,   20,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
        1,    1,    1,    1,   21,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   19,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   19,
       44,   19,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    1,    2,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    3,    2,    1,    2,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[337] =
    {   0,
        0,    0,  367,  368,   45,   48,  350,    0,  368,  368,
      368,   41,   42,  351,  368,   45,  348,  347,  346,    0,
       35,   39,   45,   52,   50,   60,   54,  327,   62,   74,
       23,   72,   79,  319,   42,   64,   90,  325,  332,  368,
      368,  114,  368,  351,  342,  109,  110,  113,  127,  368,
      368,  368,    0,  313,  333,  321,  327,  327,  318,  314,
      305,  312,  311,  324,  318,   71,  305,  308,  311,  308,
      318,  312,  316,  315,  313,  312,   99,  289,  107,  311,
      310,  292,  289,  303,  287,  294,  298,  294,  291,  286,
        0,  283,  281,  297,  279,  282,  368,  294,   38,  283,

      270,  278,  288,  278,  110,   66,  272,  368,  295,  294,
      277,  271,    0,    0,    0,  273,    0,  270,  264,    0,
      267,  279,  270,  273,  272,  257,  273,  256,  259,  267,
      257,  256,  258,  251,  263,  261,  250,  250,  258,  248,
      247,  250,  258,  253,    0,  246,    0,  243,  246,  254,
      253,  234,  228,  368,  232,  245,    0,    0,  243,  368,
      233,  236,  240,    0,  239,  223,  230,    0,  238,  107,
        0,  235,    0,  108,  222,  225,  218,  233,  368,  233,
      229,  109,  227,  116,  117,  232,    0,    0,    0,  226,
        0,  213,  118,  119,  218,    0,  217,    0,  222,  213,

      218,  217,  368,  135,  368,    0,    0,  204,  211,  221,
        0,  205,    0,  214,  203,  200,  199,  200,  197,  368,
      208,  207,  368,  200,    0,  195,  192,  194,  192,  189,
      190,  187,  199,    0,  199,  186,  183,  184,  181,    0,
        0,    0,  192,  182,  181,  180,  368,  368,  188,  178,
      176,    0,    0,    0,    0,  368,  368,  139,  368,  185,
        0,    0,  172,    0,    0,    0,    0,  179,  182,    0,
        0,    0,    0,  186,  184,  183,  170,    0,  161,  167,
      368,  368,  368,  160,  368,  167,  172,  162,  173,  164,
      163,  368,  168,  155,  160,    0,  164,  150,  154,  149,

      148,  148,  145,  158,    0,    0,  161,    0,    0,    0,
      156,  368,  157,  155,  147,  154,  153,  149,  133,  140,
      144,  139,  145,  139,  134,  112,  102,   97,   94,    0,
       62,    0,    0,  368,  176,   82
    } ;

static yyconst flex_int16_t yy_def[337] =
    {   0,
      334,    1,  334,  334,  334,  334,  334,  335,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  336,
      336,  336,  334,  334,  336,  336,  336,  336,  336,  336,
      336,  336,  334,  336,  336,  334,  336,  336,  336,  334,
      334,  334,  334,  335,  334,  334,  334,  334,  334,  334,
      334,  334,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  334,  334,  334,  334,  334,  334,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  334,  334,  334,  334,  334,  336,  336,  336,

      334,  334,  336,  336,  336,  336,  336,  334,  334,  334,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      334,  334,  334,  334,  334,  334,  334,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  334,  334,  334,  334,  336,  336,  336,  336,  334,
      334,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  334,  334,  334,  334,  334,  334,  334,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,

      336,  336,  334,  334,  334,  336,  336,  334,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  334,  334,  334,
      334,  334,  334,  334,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  334,  334,  334,  336,  336,
      336,  336,  336,  336,  336,  334,  334,  334,  334,  334,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  334,  336,  336,  336,
      334,  334,  334,  334,  334,  336,  336,  336,  336,  336,
      336,  334,  336,  336,  334,  336,  336,  336,  336,  336,

      336,  336,  336,  334,  336,  336,  336,  336,  336,  336,
      336,  334,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      336,  336,  336,    0,  334,  334
    } ;

static yyconst flex_int16_t yy_nxt[415] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,    4,   20,   20,
       20,   21,   22,   23,   24,   20,   25,   26,   27,   28,
       29,   20,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   20,   20,   40,   41,   42,   42,   42,   42,
       42,   42,   45,   45,   46,   46,   45,   85,   48,   54,
       59,  157,   55,   86,   49,  158,   56,   99,   57,   60,
       49,   70,   58,   61,   62,   64,   65,   66,   63,   76,
       71,   67,  100,   73,   53,  101,   68,   72,   77,   69,
       74,   80,  102,   78,   75,   82,   81,  123,   87,   83,

       93,  333,  124,   88,  166,   89,  167,   90,   84,   91,
       94,  103,   92,   95,   96,   42,   42,   42,   97,  104,
       45,  332,   46,   47,   45,  331,   48,  105,   49,   49,
      135,  136,   49,  138,   49,   49,  109,  109,   49,  164,
      110,  330,  215,  218,  226,  329,  139,  216,  219,  227,
      165,  229,  231,  236,  238,  246,  230,  232,  237,  239,
      281,  328,  282,  283,  321,  327,  326,  247,  325,  324,
      322,  323,  320,  319,  318,  317,  284,   44,   44,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  297,  296,

      295,  294,  293,  292,  291,  290,  289,  288,  287,  286,
      285,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  269,  268,  267,  266,  265,  264,  263,  262,
      261,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      251,  250,  249,  248,  245,  244,  243,  242,  241,  240,
      235,  234,  233,  228,  225,  224,  223,  222,  221,  220,
      217,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,

      175,  174,  173,  172,  171,  170,  169,  110,  110,  168,
      163,  162,  161,  160,  159,  156,  155,  154,  153,  152,
      151,  150,  149,  148,  147,  146,  145,  144,  143,  142,
      141,  140,  137,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,  122,  121,  120,  119,  118,  117,  116,
      115,  114,  113,  112,  111,   47,  108,  107,  106,   98,
       79,   52,   51,   50,   47,   43,  334,    3,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334
    } ;

static yyconst flex_int16_t yy_chk[415] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    6,
        6,    6,   12,   13,   12,   13,   16,   31,   16,   21,
       22,   99,   21,   31,   16,   99,   21,   35,   21,   22,
       16,   25,   21,   22,   22,   23,   23,   24,   22,   27,
       25,   24,   35,   26,  336,   36,   24,   25,   27,   24,
       26,   29,   36,   27,   26,   30,   29,   66,   32,   30,

       33,  331,   66,   32,  106,   32,  106,   32,   30,   32,
       33,   37,   32,   33,   33,   42,   42,   42,   33,   37,
       46,  329,   46,   47,   48,  328,   48,   37,   46,   47,
       77,   77,   48,   79,   46,   47,   49,   49,   48,  105,
       49,  327,  170,  174,  182,  326,   79,  170,  174,  182,
      105,  184,  185,  193,  194,  204,  184,  185,  193,  194,
      258,  325,  258,  258,  319,  324,  323,  204,  322,  321,
      319,  320,  318,  317,  316,  315,  258,  335,  335,  314,
      313,  311,  307,  304,  303,  302,  301,  300,  299,  298,
      297,  295,  294,  293,  291,  290,  289,  288,  287,  286,

      284,  280,  279,  277,  276,  275,  274,  269,  268,  263,
      260,  251,  250,  249,  246,  245,  244,  243,  239,  238,
      237,  236,  235,  233,  232,  231,  230,  229,  228,  227,
      226,  224,  222,  221,  219,  218,  217,  216,  215,  214,
      212,  210,  209,  208,  202,  201,  200,  199,  197,  195,
      192,  190,  186,  183,  181,  180,  178,  177,  176,  175,
      172,  169,  167,  166,  165,  163,  162,  161,  159,  156,
      155,  153,  152,  151,  150,  149,  148,  146,  144,  143,
      142,  141,  140,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,

      122,  121,  119,  118,  116,  112,  111,  110,  109,  107,
      104,  103,  102,  101,  100,   98,   96,   95,   94,   93,
       92,   90,   89,   88,   87,   86,   85,   84,   83,   82,
       81,   80,   78,   76,   75,   74,   73,   72,   71,   70,
       69,   68,   67,   65,   64,   63,   62,   61,   60,   59,
       58,   57,   56,   55,   54,   45,   44,   39,   38,   34,
       28,   19,   18,   17,   14,    7,    3,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "coach_lang_tok.ll"
/* -*-flex-*- */
/*
 *Copyright:

    Copyright (C) 2001 RoboCup Soccer Server Maintainance Group.
    	Patrick Riley, Tom Howard, Itsuki Noda,	Mikhail Prokopenko, Jan Wendler 

    This file is part of SoccerServer.

    SoccerServer is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 *EndCopyright:
 */
#line 27 "coach_lang_tok.ll"

#include "coach_lang_tok.h"
#include "coach_lang_par.h"
#include "types.h"

/* Definitions */
#line 652 "coach_lang_tok.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 47 "coach_lang_tok.ll"


#line 755 "coach_lang_tok.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 335 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 368 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "coach_lang_tok.ll"
{ return RCSS_CLANG_LP;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "coach_lang_tok.ll"
{ return RCSS_CLANG_RP;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "coach_lang_tok.ll"
{ return RCSS_CLANG_LB;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "coach_lang_tok.ll"
{ return RCSS_CLANG_RB;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 54 "coach_lang_tok.ll"
{ return RCSS_CLANG_SAY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 55 "coach_lang_tok.ll"
{ return RCSS_CLANG_HEAR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "coach_lang_tok.ll"
{ *M_lexed_val = LEFT; return RCSS_CLANG_COACH_SIDE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "coach_lang_tok.ll"
{ *M_lexed_val = RIGHT; return RCSS_CLANG_COACH_SIDE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "coach_lang_tok.ll"
{ return RCSS_CLANG_META;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "coach_lang_tok.ll"
{ return RCSS_CLANG_FREEFORM;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "coach_lang_tok.ll"
{ return RCSS_CLANG_UNSUPP;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "coach_lang_tok.ll"
{ return RCSS_CLANG_INFO; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "coach_lang_tok.ll"
{ return RCSS_CLANG_ADVICE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEFINE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEFINEC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEFINED; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEFINER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEFINEA; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "coach_lang_tok.ll"
{ return RCSS_CLANG_VER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 73 "coach_lang_tok.ll"
{ return RCSS_CLANG_NULL_REGION; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 74 "coach_lang_tok.ll"
{ return RCSS_CLANG_QUAD; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 75 "coach_lang_tok.ll"
{ return RCSS_CLANG_ARC; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 76 "coach_lang_tok.ll"
{ return RCSS_CLANG_PT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 77 "coach_lang_tok.ll"
{ return RCSS_CLANG_REG; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 78 "coach_lang_tok.ll"
{ return RCSS_CLANG_TRI; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "coach_lang_tok.ll"
{ return RCSS_CLANG_REC; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 81 "coach_lang_tok.ll"
{ return RCSS_CLANG_BALL;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 83 "coach_lang_tok.ll"
{ return RCSS_CLANG_POS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 84 "coach_lang_tok.ll"
{ return RCSS_CLANG_HOME;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 85 "coach_lang_tok.ll"
{ return RCSS_CLANG_BALLTO;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 86 "coach_lang_tok.ll"
{ return RCSS_CLANG_MARK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 87 "coach_lang_tok.ll"
{ return RCSS_CLANG_MARK_LINE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "coach_lang_tok.ll"
{ return RCSS_CLANG_OFFLINE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "coach_lang_tok.ll"
{ return RCSS_CLANG_HTYPE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::Pass; return RCSS_CLANG_BMOVE_TOKEN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::Dribble; return RCSS_CLANG_BMOVE_TOKEN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 92 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::Clear; return RCSS_CLANG_BMOVE_TOKEN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::Score; return RCSS_CLANG_BMOVE_TOKEN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "coach_lang_tok.ll"
{ *M_lexed_val = true; return RCSS_CLANG_DO_DONT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 96 "coach_lang_tok.ll"
{ *M_lexed_val = false; return RCSS_CLANG_DO_DONT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 98 "coach_lang_tok.ll"
{ *M_lexed_val = true; return RCSS_CLANG_TEAM; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 99 "coach_lang_tok.ll"
{ *M_lexed_val = false; return RCSS_CLANG_TEAM; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 101 "coach_lang_tok.ll"
{ return RCSS_CLANG_CLEAR; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 103 "coach_lang_tok.ll"
{ return RCSS_CLANG_TRUE_KW; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 104 "coach_lang_tok.ll"
{ return RCSS_CLANG_FALSE_KW; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 105 "coach_lang_tok.ll"
{ return RCSS_CLANG_PPOS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 106 "coach_lang_tok.ll"
{ return RCSS_CLANG_BPOS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 107 "coach_lang_tok.ll"
{ return RCSS_CLANG_BOWNER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 108 "coach_lang_tok.ll"
{ return RCSS_CLANG_AND; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 109 "coach_lang_tok.ll"
{ return RCSS_CLANG_OR; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "coach_lang_tok.ll"
{ return RCSS_CLANG_NOT; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 111 "coach_lang_tok.ll"
{ return RCSS_CLANG_PLAY_MODE_KW; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 112 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::BeforeKickOff;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 114 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::TimeOver;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 116 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::PlayOn;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::KickOff_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 120 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::KickOff_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 122 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::KickIn_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 124 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::KickIn_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 126 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::FreeKick_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 128 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::FreeKick_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 130 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::CornerKick_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 132 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::CornerKick_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::GoalKick_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 136 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::GoalKick_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 138 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::GoalieCatch_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 140 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::GoalieCatch_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::AfterGoal_Our;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 144 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::clang::AfterGoal_Opp;
            return RCSS_CLANG_PLAY_MODE; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "coach_lang_tok.ll"
{ return RCSS_CLANG_TIME; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "coach_lang_tok.ll"
{ return RCSS_CLANG_OPP_GOAL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "coach_lang_tok.ll"
{ return RCSS_CLANG_OUR_GOAL; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "coach_lang_tok.ll"
{ return RCSS_CLANG_GOAL_DIFF; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "coach_lang_tok.ll"
{ return RCSS_CLANG_UNUM; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 155 "coach_lang_tok.ll"
{ return RCSS_CLANG_PASS; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 156 "coach_lang_tok.ll"
{ return RCSS_CLANG_DRIBBLE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 157 "coach_lang_tok.ll"
{ return RCSS_CLANG_SHOOT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 158 "coach_lang_tok.ll"
{ return RCSS_CLANG_HOLD; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 159 "coach_lang_tok.ll"
{ return RCSS_CLANG_INTERCEPT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 160 "coach_lang_tok.ll"
{ return RCSS_CLANG_TACKLE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "coach_lang_tok.ll"
{ return RCSS_CLANG_RULE; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "coach_lang_tok.ll"
{ *M_lexed_val = true; return RCSS_CLANG_ON_OFF; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "coach_lang_tok.ll"
{ *M_lexed_val = false; return RCSS_CLANG_ON_OFF; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "coach_lang_tok.ll"
{ return RCSS_CLANG_ALL; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEL; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 167 "coach_lang_tok.ll"
{ return RCSS_CLANG_DEFRULE; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "coach_lang_tok.ll"
{ return RCSS_CLANG_MODEL; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 169 "coach_lang_tok.ll"
{ return RCSS_CLANG_DIREC; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 172 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::CompOp::less();
            return RCSS_CLANG_L; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 174 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::CompOp::lessEqual();
            return RCSS_CLANG_LE; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 176 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::CompOp::equal();
            return RCSS_CLANG_E; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 178 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::CompOp::notEqual();
            return RCSS_CLANG_NE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 180 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::CompOp::greaterEqual();
            return RCSS_CLANG_GE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 182 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::CompOp::greater();
            return RCSS_CLANG_G; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 185 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::ArithOp::plus();
             return RCSS_CLANG_PLUS; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 187 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::ArithOp::minus();
            return RCSS_CLANG_MINUS; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 189 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::ArithOp::mult();
            return RCSS_CLANG_MULT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 191 "coach_lang_tok.ll"
{ *M_lexed_val = rcss::util::ArithOp::div();
            return RCSS_CLANG_DIV; }
	YY_BREAK
case 99:
/* rule 99 can match eol */
YY_RULE_SETUP
#line 195 "coach_lang_tok.ll"
;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 198 "coach_lang_tok.ll"
{ *M_lexed_val = atoi(yytext); return RCSS_CLANG_INT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 199 "coach_lang_tok.ll"
{ *M_lexed_val = atoi(yytext); return RCSS_CLANG_INT; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 200 "coach_lang_tok.ll"
{ *M_lexed_val = atof(yytext); return RCSS_CLANG_REAL; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 201 "coach_lang_tok.ll"
{ *M_lexed_val = atof(yytext); return RCSS_CLANG_REAL; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 203 "coach_lang_tok.ll"
{ *M_lexed_val = yytext ;
													      return RCSS_CLANG_STR; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 206 "coach_lang_tok.ll"
{ *M_lexed_val = yytext;
												 return RCSS_CLANG_VAR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 209 "coach_lang_tok.ll"
{ return RCSS_CLANG_ERROR; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 211 "coach_lang_tok.ll"
ECHO;
	YY_BREAK
#line 1403 "coach_lang_tok.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;

	yy_state_buf = 0;

}

yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	RCSSCLangFlexLexerfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
}

void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					RCSSCLangFlexLexerrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 335 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 335 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 334);

	return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) RCSSCLangFlexLexeralloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) RCSSCLangFlexLexeralloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		RCSSCLangFlexLexerfree((void *) b->yy_ch_buf  );

	RCSSCLangFlexLexerfree((void *) b  );
}

extern "C" int isatty (int );

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)RCSSCLangFlexLexeralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)RCSSCLangFlexLexerrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) RCSSCLangFlexLexeralloc(new_size  );

		else
			(yy_start_stack) = (int *) RCSSCLangFlexLexerrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *RCSSCLangFlexLexeralloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *RCSSCLangFlexLexerrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void RCSSCLangFlexLexerfree (void * ptr )
{
	free( (char *) ptr );	/* see RCSSCLangFlexLexerrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 211 "coach_lang_tok.ll"



/* int RCSS_CLANG_parse( void* );*/

/* namespace rcss*/
/* {*/
/*   namespace clang*/
/*   {*/
/*     int */
/*     Parser::parse( const char* s, Parser::Param& param ) */
/*     {*/
/*       YY_BUFFER_STATE yybuffstateCurr;*/

/*       yybuffstateCurr = yy_scan_string(s);*/
    
/*       int ret = RCSS_CLANG_parse( (void*)&param );*/
/*       yy_delete_buffer(yybuffstateCurr);*/
/*       return ret;*/
/*     }*/
/*   };*/
/* };*/

