all:
	cd ./RL-Glue/Examples/Glue_Only && make
	cd ./agents/RandomAgent/ && make
	cd ./trainers/consoleTrainerJava/ && make

clean:
	cd ./RL-Glue/Examples/Glue_Only && make clean
	cd ./agents/RandomAgent/ && make clean
	cd ./trainers/consoleTrainerJava/ && make clean