all:
	cd ./RL-Glue/Examples/Glue_Only && make
	cd ./agents/randomAgentJava/ && make
	cd ./agents/tetrisAgentJava/ && make
	cd ./agents/mountainCarAgentCPP/ && make
	cd ./agents/realTimeStrategyAgentJava/ && make
	cd ./trainers/consoleTrainerJava/ && make
	cd ./trainers/consoleTrainerCPP/ && make
	cd ./trainers/consoleRealTimeStrategyTrainerJava/ && make

clean:
	cd ./RL-Glue/Examples/Glue_Only && make clean
	cd ./agents/randomAgentJava/ && make clean
	cd ./agents/tetrisAgentJava/ && make clean
	cd ./agents/mountainCarAgentCPP/ && make clean
	cd ./agents/realTimeStrategyAgentJava/ && make clean
	cd ./trainers/consoleTrainerJava/ && make clean
	cd ./trainers/consoleTrainerCPP/ && make clean
	cd ./trainers/consoleRealTimeStrategyTrainerJava/ && make clean
	